local _, ns = ...

-- Home-grid places. Loot still comes only from what this character records.
-- A screenshot can replace the placeholder icon later. Put the file in
-- PhatLewtDb/Art and set the path here with no extension:
--   ["Elwynn Forest"] = "Interface\\AddOns\\PhatLewtDb\\Art\\ElwynnForest",
ns.PLACE_ART = {}

ns.PLACES = {
	{ name = "Alterac Mountains", kind = "world" },
	{ name = "Arathi Highlands", kind = "world" },
	{ name = "Ashenvale", kind = "world" },
	{ name = "Azshara", kind = "world" },
	{ name = "Badlands", kind = "world" },
	{ name = "Blackrock Mountain", kind = "world" },
	{ name = "Blasted Lands", kind = "world" },
	{ name = "Burning Steppes", kind = "world" },
	{ name = "Darkshore", kind = "world" },
	{ name = "Deadwind Pass", kind = "world" },
	{ name = "Desolace", kind = "world" },
	{ name = "Dun Morogh", kind = "world" },
	{ name = "Durotar", kind = "world" },
	{ name = "Duskwood", kind = "world" },
	{ name = "Dustwallow Marsh", kind = "world" },
	{ name = "Eastern Plaguelands", kind = "world" },
	{ name = "Elwynn Forest", kind = "world" },
	{ name = "Felwood", kind = "world" },
	{ name = "Feralas", kind = "world" },
	{ name = "Hillsbrad Foothills", kind = "world" },
	{ name = "Loch Modan", kind = "world" },
	{ name = "Moonglade", kind = "world" },
	{ name = "Mulgore", kind = "world" },
	{ name = "Redridge Mountains", kind = "world" },
	{ name = "Searing Gorge", kind = "world" },
	{ name = "Silithus", kind = "world" },
	{ name = "Silverpine Forest", kind = "world" },
	{ name = "Stonetalon Mountains", kind = "world" },
	{ name = "Stranglethorn Vale", kind = "world" },
	{ name = "Swamp of Sorrows", kind = "world" },
	{ name = "Tanaris", kind = "world" },
	{ name = "Teldrassil", kind = "world" },
	{ name = "The Barrens", kind = "world" },
	{ name = "The Hinterlands", kind = "world" },
	{ name = "Thousand Needles", kind = "world" },
	{ name = "Tirisfal Glades", kind = "world" },
	{ name = "Un'Goro Crater", kind = "world" },
	{ name = "Western Plaguelands", kind = "world" },
	{ name = "Westfall", kind = "world" },
	{ name = "Wetlands", kind = "world" },
	{ name = "Winterspring", kind = "world" },

	{ name = "Blackfathom Deeps", kind = "dungeon" },
	{ name = "Blackrock Depths", kind = "dungeon" },
	{ name = "Dire Maul", kind = "dungeon" },
	{ name = "Gnomeregan", kind = "dungeon" },
	{ name = "Lower Blackrock Spire", kind = "dungeon" },
	{ name = "Maraudon", kind = "dungeon" },
	{ name = "Ragefire Chasm", kind = "dungeon" },
	{ name = "Razorfen Downs", kind = "dungeon" },
	{ name = "Razorfen Kraul", kind = "dungeon" },
	{ name = "Scarlet Monastery", kind = "dungeon" },
	{ name = "Scholomance", kind = "dungeon" },
	{ name = "Shadowfang Keep", kind = "dungeon" },
	{ name = "Stratholme", kind = "dungeon" },
	{ name = "The Deadmines", kind = "dungeon", aliases = { "Deadmines" } },
	{ name = "The Stockade", kind = "dungeon", aliases = { "Stormwind Stockade", "Stockade" } },
	{ name = "Uldaman", kind = "dungeon" },
	{ name = "Upper Blackrock Spire", kind = "dungeon" },
	{ name = "Wailing Caverns", kind = "dungeon" },
	{ name = "Zul'Farrak", kind = "dungeon" },
	{
		name = "Sunken Temple",
		kind = "dungeon",
		aliases = { "The Temple of Atal'Hakkar", "Temple of Atal'Hakkar" },
	},

	{ name = "Blackwing Lair", kind = "raid" },
	{ name = "Molten Core", kind = "raid" },
	{ name = "Naxxramas", kind = "raid" },
	{ name = "Onyxia's Lair", kind = "raid" },
	{ name = "Ruins of Ahn'Qiraj", kind = "raid" },
	{ name = "Temple of Ahn'Qiraj", kind = "raid", aliases = { "Ahn'Qiraj" } },
	{ name = "Zul'Gurub", kind = "raid" },
}
